// ─── PRODUCT DATA ────────────────────────────────────────────────────────────
const products = [

  // ─── DOORS ───────────────────────────────────────────────────────────────

  // DOORS — Main Door
  {
    id: 1, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 × 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Modern high quality kiln dried wood door.',
    image: './assets/doors/door1.jpg',
    thumb: './assets/doors/door1.jpg',
  },
  {
    id: 2, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 × 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Modern high quality kiln dried wood door.',
    image: './assets/doors/door2.jpg',
    thumb: './assets/doors/door2.jpg',
  },
  {
    id: 3, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 × 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Modern high quality kiln dried wood door.',
    image: './assets/doors/door3.jpg',
    thumb: './assets/doors/door3.jpg',
  },
  {
    id: 4, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 × 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Modern high quality kiln dried wood door.',
    image: './assets/doors/door24.png',
    thumb: './assets/doors/door24.png',
  },
  {
    id: 5, category: 'Doors', doorType: 'Main Door', name: 'Main Door Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door36.png',
    thumb: './assets/doors/door36.png',
  },
  {
    id: 6, category: 'Doors', doorType: 'Main Door', name: 'Main Door Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door37.png',
    thumb: './assets/doors/door37.png',
  },
  {
    id: 7, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door25.jpg',
    thumb: './assets/doors/door25.jpg',
  },
  {
    id: 8, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Lamborghini door.',
    image: './assets/doors/door26.jpg',
    thumb: './assets/doors/door26.jpg',
  },
  {
    id: 9, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door27.jpg',
    thumb: './assets/doors/door27.jpg',
  },
  {
    id: 10, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried One Piece Gear Five door.',
    image: './assets/doors/door28.jpg',
    thumb: './assets/doors/door28.jpg',
  },
  {
    id: 11, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door29.jpg',
    thumb: './assets/doors/door29.jpg',
  },
  {
    id: 12, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door30.jpg',
    thumb: './assets/doors/door30.jpg',
  },
  {
    id: 13, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door31.jpeg',
    thumb: './assets/doors/door31.jpeg',
  },
  {
    id: 14, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Main Door',
    material: 'Solid Kiln Dried Wood', dimensions: '140 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Main Door.',
    image: './assets/doors/door32.jpeg',
    thumb: './assets/doors/door32.jpeg',
  },
  {
    id: 15, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door33.jpeg',
    thumb: './assets/doors/door33.jpeg',
  },
  {
    id: 16, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door35.jpeg',
    thumb: './assets/doors/door35.jpeg',
  },
  {
    id: 17, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door39.png',
    thumb: './assets/doors/door39.png',
  },
  {
    id: 18, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door40.png',
    thumb: './assets/doors/door40.png',
  },
  {
    id: 19, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door41.png',
    thumb: './assets/doors/door41.png',
  },
  {
    id: 20, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door42.png',
    thumb: './assets/doors/door42.png',
  },
  {
    id: 21, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door43.png',
    thumb: './assets/doors/door43.png',
  },
  {
    id: 22, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door44.png',
    thumb: './assets/doors/door44.png',
  },
  {
    id: 23, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door45.png',
    thumb: './assets/doors/door45.png',
  },
  {
    id: 24, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door47.png',
    thumb: './assets/doors/door47.png',
  },

  // DOORS — Ordinary
  {
    id: 25, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door7.png',
    thumb: './assets/doors/door7.png',
  },
  {
    id: 26, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door8.png',
    thumb: './assets/doors/door8.png',
  },
  {
    id: 27, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door9.png',
    thumb: './assets/doors/door9.png',
  },
  {
    id: 28, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door10.png',
    thumb: './assets/doors/door10.png',
  },
  {
    id: 29, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door11.png',
    thumb: './assets/doors/door11.png',
  },
  {
    id: 30, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door12.png',
    thumb: './assets/doors/door12.png',
  },
  {
    id: 31, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door13.png',
    thumb: './assets/doors/door13.png',
  },
  {
    id: 32, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door14.jpg',
    thumb: './assets/doors/door14.jpg',
  },
  {
    id: 33, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door15.png',
    thumb: './assets/doors/door15.png',
  },
  {
    id: 34, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'A masterpiece of Filipino craftsmanship. Hand-carved from solid Narra with intricate floral motifs and a rich, lustrous finish.',
    image: './assets/doors/door16.png',
    thumb: './assets/doors/door16.png',
  },
  {
    id: 35, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'A masterpiece of Filipino craftsmanship. Hand-carved from solid Narra with intricate floral motifs and a rich, lustrous finish.',
    image: './assets/doors/door17.png',
    thumb: './assets/doors/door17.png',
  },
  {
    id: 36, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door18.png',
    thumb: './assets/doors/door18.png',
  },
  {
    id: 37, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door19.png',
    thumb: './assets/doors/door19.png',
  },
  {
    id: 38, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door20.png',
    thumb: './assets/doors/door20.png',
  },
  {
    id: 39, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door21.png',
    thumb: './assets/doors/door21.png',
  },
  {
    id: 40, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door22.png',
    thumb: './assets/doors/door22.png',
  },
  {
    id: 41, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door23.png',
    thumb: './assets/doors/door23.png',
  },
  {
    id: 42, category: 'Doors', doorType: 'Ordinary', name: 'Ordinary Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door4.png',
    thumb: './assets/doors/door4.png',
  },
  {
    id: 43, category: 'Doors', doorType: 'Ordinary', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door34.jpeg',
    thumb: './assets/doors/door34.jpeg',
  },
  {
    id: 44, category: 'Doors', doorType: 'Ordinary', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door5.png',
    thumb: './assets/doors/door5.png',
  },
  {
    id: 45, category: 'Doors', doorType: 'Ordinary', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/door6.png',
    thumb: './assets/doors/door6.png',
  },

  // DOORS — Double Door
  {
    id: 46, category: 'Doors', doorType: 'Double Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried door.',
    image: './assets/doors/doubledoor1.png',
    thumb: './assets/doors/doubledoor1.png',
  },

  // DOORS — Flush Door
  {
    id: 47, category: 'Doors', doorType: 'Flush Door', name: 'Flush Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door38.png',
    thumb: './assets/doors/door38.png',
  },
  {
    id: 48, category: 'Doors', doorType: 'Flush Door', name: 'Flush Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door46.png',
    thumb: './assets/doors/door46.png',
  },
  {
    id: 49, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door48.png',
    thumb: './assets/doors/door48.png',
  },
  {
    id: 50, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door49.png',
    thumb: './assets/doors/door49.png',
  },
  {
    id: 51, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door50.png',
    thumb: './assets/doors/door50.png',
  },
  {
    id: 52, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door51.png',
    thumb: './assets/doors/door51.png',
  },
  {
    id: 53, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door52.png',
    thumb: './assets/doors/door52.png',
  },
  {
    id: 54, category: 'Doors', doorType: 'Double Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/doubledoor2.png',
    thumb: './assets/doors/doubledoor2.png',
  },
  {
    id: 55, category: 'Doors', doorType: 'Double Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/doubledoor3.png',
    thumb: './assets/doors/doubledoor3.png',
  },
  {
    id: 56, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door53.png',
    thumb: './assets/doors/door53.png',
  },
  {
    id: 57, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door54.png',
    thumb: './assets/doors/door54.png',
  },
  {
    id: 58, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door55.png',
    thumb: './assets/doors/door55.png',
  },
  {
    id: 59, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door56.png',
    thumb: './assets/doors/door56.png',
  },
  {
    id: 60, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door57.png',
    thumb: './assets/doors/door57.png',
  },
  {
    id: 61, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door58.png',
    thumb: './assets/doors/door58.png',
  },
  {
    id: 62, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door59.png',
    thumb: './assets/doors/door59.png',
  },
  {
    id: 63, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door60.png',
    thumb: './assets/doors/door60.png',
  },
  {
    id: 64, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door61.png',
    thumb: './assets/doors/door61.png',
  },
  {
    id: 65, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door62.png',
    thumb: './assets/doors/door62.png',
  },
  {
    id: 66, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door63.png',
    thumb: './assets/doors/door63.png',
  },
  {
    id: 67, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door64.png',
    thumb: './assets/doors/door64.png',
  },
  {
    id: 68, category: 'Doors', doorType: 'Double Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/doubledoor5.png',
    thumb: './assets/doors/doubledoor5.png',
  },
  {
    id: 69, category: 'Doors', doorType: 'Double Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/doubledoor6.png',
    thumb: './assets/doors/doubledoor6.png',
  },
  {
    id: 70, category: 'Doors', doorType: 'Double Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/doubledoor7.png',
    thumb: './assets/doors/doubledoor7.png',
  },

  {
    id: 71, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door65.jpg',
    thumb: './assets/doors/door65.jpg',
  },

  {
    id: 72, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door66.png',
    thumb: './assets/doors/door66.png',
  },

  {
    id: 73, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door67.png',
    thumb: './assets/doors/door67.png',
  },

  {
    id: 74, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door68.png',
    thumb: './assets/doors/door68.png',
  },

  {
    id: 75, category: 'Doors', doorType: 'Ordinary', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door69.png',
    thumb: './assets/doors/door69.png',
  },

  {
    id: 76, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door70.png',
    thumb: './assets/doors/door70.png',
  },

  {
    id: 77, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door71.png',
    thumb: './assets/doors/door71.png',
  },

  {
    id: 78, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door72.png',
    thumb: './assets/doors/door72.png',
  },

  {
    id: 79, category: 'Doors', doorType: 'Main Door', name: 'Solid Kiln Dried Wood Door',
    material: 'Solid Kiln Dried Wood', dimensions: '80-90 x 210cm',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Ordinary high quality kiln dried wood door.',
    image: './assets/doors/door73.png',
    thumb: './assets/doors/door73.png',
  },

  

  // ─── CABINETS (IDs start at 71) ──────────────────────────────────────────
  {
    id: 151, category: 'Cabinets', name: 'MDF Green Spec 810 Wood Cabinet',
    material: 'MDF Green Spec 810 Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Cabinet.',
    image: './assets/cabinet/cabinet1.png',
    thumb: './assets/cabinet/cabinet1.png',
  },
  {
    id: 152, category: 'Cabinets', name: 'MDF Green Spec 810 Wood Cabinet',
    material: 'MDF Green Spec 810 Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Cabinet.',
    image: './assets/cabinet/cabinet2.png',
    thumb: './assets/cabinet/cabinet2.png',
  },
  {
    id: 153, category: 'Cabinets', name: 'MDF Green Spec 810 Wood Cabinet',
    material: 'MDF Green Spec 810 Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Cabinet.',
    image: './assets/cabinet/cabinet3.png',
    thumb: './assets/cabinet/cabinet3.png',
  },
  {
    id: 154, category: 'Cabinets', name: 'MDF Green Spec 810 Wood Cabinet',
    material: 'MDF Green Spec 810 Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Cabinet.',
    image: './assets/cabinet/cabinet4.png',
    thumb: './assets/cabinet/cabinet4.png',
    images: [
      './assets/cabinet/cabinet4.png',
      './assets/cabinet/cabinet4.1.png',
    ],
  },
  {
    id: 155, category: 'Cabinets', name: 'MDF Green Spec 810 Wood Cabinet',
    material: 'MDF Green Spec 810 Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Cabinet.',
    image: './assets/cabinet/cabinet5.png',
    thumb: './assets/cabinet/cabinet5.png',
  },
  {
    id: 156, category: 'Cabinets', name: 'MDF Green Spec 810 Wood Cabinet',
    material: 'MDF Green Spec 810 Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Cabinet.',
    image: './assets/cabinet/cabinet6.png',
    thumb: './assets/cabinet/cabinet6.png',
  },

  // ─── DINING TABLES (IDs start at 141) ────────────────────────────────────
  {
    id: 301, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table1.png',
    thumb: './assets/dining/dining-table1.png',
  },
  {
    id: 302, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table2.png',
    thumb: './assets/dining/dining-table2.png',
  },
  {
    id: 303, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table3.png',
    thumb: './assets/dining/dining-table3.png',
  },
  {
    id: 304, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table4.png',
    thumb: './assets/dining/dining-table4.png',
  },
  {
    id: 305, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table5.png',
    thumb: './assets/dining/dining-table5.png',
  },
  {
    id: 306, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table6.png',
    thumb: './assets/dining/dining-table6.png',
  },
  {
    id: 307, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table7.png',
    thumb: './assets/dining/dining-table7.png',
  },
  {
    id: 308, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table8.png',
    thumb: './assets/dining/dining-table8.png',
  },
  {
    id: 309, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table9.png',
    thumb: './assets/dining/dining-table9.png',
  },
  {
    id: 310, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table10.png',
    thumb: './assets/dining/dining-table10.png',
  },
  {
    id: 311, category: 'Dining Tables', name: 'Solid Kiln dried Wood Dining Table',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried dining table.',
    image: './assets/dining/dining-table11.png',
    thumb: './assets/dining/dining-table11.png',
  },

  // ─── BED FRAMES (IDs start at 211) ───────────────────────────────────────
  {
    id: 451, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe1.png',
    thumb: './assets/bedframe/bedframe1.png',
  },
  {
    id: 452, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe2.png',
    thumb: './assets/bedframe/bedframe2.png',
  },
  {
    id: 453, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe3.png',
    thumb: './assets/bedframe/bedframe3.png',
  },
  {
    id: 454, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe4.png',
    thumb: './assets/bedframe/bedframe4.png',
  },
  {
    id: 455, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe5.png',
    thumb: './assets/bedframe/bedframe5.png',
  },
  {
    id: 456, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe6.png',
    thumb: './assets/bedframe/bedframe6.png',
  },
  {
    id: 457, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe7.png',
    thumb: './assets/bedframe/bedframe7.png',
  },
  {
    id: 458, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe8.png',
    thumb: './assets/bedframe/bedframe8.png',
  },
  {
    id: 459, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe9.png',
    thumb: './assets/bedframe/bedframe9.png',
  },
  {
    id: 460, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe10.png',
    thumb: './assets/bedframe/bedframe10.png',
  },
  {
    id: 461, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe11.png',
    thumb: './assets/bedframe/bedframe11.png',
  },

  {
    id: 467, category: 'Bed Frames', name: 'Solid Kiln dried Wood Bed Frame',
    material: 'Solid Kiln Dried Wood', dimensions: '',
    finishes: ['Mahogany Wood', 'Varnished', 'Sand Beige'],
    description: 'Solid high quality kiln dried Bed Frame.',
    image: './assets/bedframe/bedframe12.png',
    thumb: './assets/bedframe/bedframe12.png',
  },
];